package main

import (
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

const cmdTmpl = `// Code generated by gen-platform-cmds. DO NOT EDIT.
package generated

import (
	"context"
	"encoding/json"

	"github.com/spf13/cobra"
	"github.com/yomiroco/yomiro-cli/internal/platform/client"
)

// New{{.GoTag}}Cmd returns the cobra command tree for {{.Tag}}.
func New{{.GoTag}}Cmd(c *client.ClientWithResponses) *cobra.Command {
	root := &cobra.Command{
		Use:   "{{.CLITag}}",
		Short: "Manage {{.Tag}}",
	}
{{range .Subs}}
	{
		cmd := &cobra.Command{
			Use:   "{{.Use}}",
			Short: "{{.Summary}}",
			RunE: func(cmd *cobra.Command, args []string) error {
				ctx := context.Background()
				_ = ctx
				_ = c
				out := map[string]string{"todo": "{{.OpID}}"}
				return json.NewEncoder(cmd.OutOrStdout()).Encode(out)
			},
		}
		root.AddCommand(cmd)
	}
{{end}}
	return root
}
`

type tmplData struct {
	Tag    string
	GoTag  string
	CLITag string
	Subs   []subCmd
}

type subCmd struct {
	Use     string
	OpID    string
	Summary string
}

func EmitGroup(tag string, ops []Operation, outDir string) error {
	t := template.Must(template.New("cmd").Parse(cmdTmpl))
	var subs []subCmd
	for _, op := range ops {
		subs = append(subs, subCmd{
			Use:     verbForOp(op),
			OpID:    exportName(op.OperationID),
			Summary: escape(op.Summary),
		})
	}
	data := tmplData{
		Tag:    tag,
		GoTag:  goName(tag),
		CLITag: cliName(tag),
		Subs:   subs,
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	out := filepath.Join(outDir, cliName(tag)+".gen.go")
	f, err := os.Create(out)
	if err != nil {
		return err
	}
	defer f.Close()
	return t.Execute(f, data)
}

func verbForOp(op Operation) string {
	hasIDParam := strings.Contains(op.Path, "{")
	switch op.Method {
	case "GET":
		if hasIDParam {
			return "get"
		}
		return "list"
	case "POST":
		return "create"
	case "PUT", "PATCH":
		return "update"
	case "DELETE":
		return "delete"
	}
	return "exec"
}

func exportName(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool { return r == '_' || r == '-' })
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}

func goName(tag string) string {
	return exportName(strings.ReplaceAll(tag, "-", "_"))
}

func cliName(tag string) string {
	return strings.ReplaceAll(strings.ToLower(tag), "_", "-")
}

func escape(s string) string {
	r := strings.NewReplacer(
		"\"", "'",
		"\n", " ",
		"`", "'",
		"\\", "/",
	)
	return r.Replace(s)
}
