package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

const cmdTmpl = `// Code generated by gen-platform-cmds. DO NOT EDIT.
package generated

import (
{{if .NeedsFmt}}	"fmt"

{{end}}{{if .NeedsStrconv}}	"strconv"

{{end}}{{if .NeedsUUID}}	"github.com/google/uuid"
{{end}}	"github.com/spf13/cobra"

{{if .NeedsOutput}}	"github.com/yomiroco/yomiro-cli/internal/output"
{{end}}{{if .NeedsBindings}}	"github.com/yomiroco/yomiro-cli/internal/platform/bindings"
{{end}}	"github.com/yomiroco/yomiro-cli/internal/platform/client"
)

// New{{.GoTag}}Cmd returns the cobra command tree for {{.Tag}}. The
// getClient factory is consulted at request time so the persistent
// --api-url / --token flags can override the credentials-store defaults.
func New{{.GoTag}}Cmd(getClient func() *client.ClientWithResponses) *cobra.Command {
	root := &cobra.Command{
		Use:   "{{.CLITag}}",
		Short: "Manage {{.Tag}}",
	}
{{range .Subs}}
	{
{{if .Skipped}}		cmd := &cobra.Command{
			Use:   "{{.Use}}",
			Short: "{{.Summary}}",
			RunE: func(cmd *cobra.Command, args []string) error {
				return fmt.Errorf("operation {{.OpID}} is not exposed by the generated client (multipart body or unsupported schema); use the platform UI or REST directly")
			},
		}
		root.AddCommand(cmd)
{{else}}{{if .HasParams}}		var params client.{{.OpID}}Params
{{end}}{{if .HasBody}}		var bodyJSON string
{{end}}{{if .HasSkeleton}}		var skeleton bool
{{end}}		cmd := &cobra.Command{
			Use:   "{{.Use}}{{range .PathParams}} <{{.Name}}>{{end}}",
			Short: "{{.Summary}}",
{{if .Long}}			Long: {{.Long}},
{{end}}{{if .PathParams}}			Args:  cobra.ExactArgs({{len .PathParams}}),
{{end}}			RunE: func(cmd *cobra.Command, args []string) error {
{{if .HasSkeleton}}				if skeleton {
					fmt.Fprintln(cmd.OutOrStdout(), {{.SkeletonConst}})
					return nil
				}
{{end}}				ctx := cmd.Context()
{{range $i, $p := .PathParams}}{{if eq $p.GoType "uuid.UUID"}}				_arg{{$i}}, err := uuid.Parse(args[{{$i}}])
				if err != nil { return fmt.Errorf("path arg <{{$p.Name}}>: %w", err) }
{{else if eq $p.GoType "int"}}				_arg{{$i}}, err := strconv.Atoi(args[{{$i}}])
				if err != nil { return fmt.Errorf("path arg <{{$p.Name}}>: %w", err) }
{{else}}				_arg{{$i}} := args[{{$i}}]
{{end}}{{end}}{{if .HasBody}}				var body client.{{.OpID}}JSONRequestBody
				if err := bindings.LoadJSONBody(bodyJSON, &body); err != nil { return err }
{{end}}				resp, err := getClient().{{.OpID}}WithResponse(ctx{{range $i, $p := .PathParams}}, _arg{{$i}}{{end}}{{if .HasParams}}, &params{{end}}{{if .HasBody}}, body{{end}})
				if err != nil { return err }
				return output.RenderResponse(cmd, resp)
			},
		}
{{if .HasParams}}		bindings.DefineQueryFlags(cmd, &params)
{{end}}{{if .HasBody}}		cmd.Flags().StringVar(&bodyJSON, "json-body", "", "Request body as JSON (literal or @file)")
{{end}}{{if .HasSkeleton}}		cmd.Flags().BoolVar(&skeleton, "skeleton", false, "Print a JSON skeleton of the request body and exit")
		cmd.MarkFlagsOneRequired("json-body", "skeleton")
		cmd.MarkFlagsMutuallyExclusive("json-body", "skeleton")
{{else if .HasBody}}		_ = cmd.MarkFlagRequired("json-body")
{{end}}		root.AddCommand(cmd)
{{end}}	}
{{end}}
	return root
}
`

type tmplData struct {
	Tag           string
	GoTag         string
	CLITag        string
	Subs          []subCmd
	NeedsFmt      bool
	NeedsUUID     bool
	NeedsStrconv  bool
	NeedsOutput   bool
	NeedsBindings bool
}

type subCmd struct {
	Use           string
	OpID          string
	Summary       string
	PathParams    []PathParam
	HasParams     bool
	HasBody       bool
	HasSkeleton   bool   // body schema is well-known enough to render a --skeleton template
	Long          string // pre-escaped Go string literal for cobra Long (or "")
	SkeletonConst string // pre-escaped Go string literal containing the JSON skeleton
	Skipped       bool   // operation isn't exposed by the generated client
}

func EmitGroup(tag string, ops []Operation, methods map[string]ClientMethod, outDir string) error {
	t := template.Must(template.New("cmd").Parse(cmdTmpl))
	verbs := assignVerbs(tag, ops)
	subs := make([]subCmd, 0, len(ops))
	var needsUUID, needsStrconv, needsOutput, needsFmt, needsBindings bool
	for i, op := range ops {
		opID := exportName(op.OperationID)
		s := subCmd{
			Use:     verbs[i],
			OpID:    opID,
			Summary: escape(op.Summary),
		}
		// Client's AST is the source of truth: skip operations oapi-codegen
		// didn't produce a typed WithResponse for (multipart bodies, etc.).
		m, ok := methods[opID]
		if !ok {
			s.Skipped = true
			needsFmt = true
		} else {
			s.PathParams = m.PathArgs
			s.HasParams = m.HasParams
			s.HasBody = m.HasBody
			needsOutput = true
			if m.HasParams || m.HasBody {
				needsBindings = true
			}
			for _, pp := range m.PathArgs {
				switch pp.GoType {
				case "uuid.UUID":
					needsUUID = true
					needsFmt = true
				case "int":
					needsStrconv = true
					needsFmt = true
				}
			}
			if m.HasBody && len(op.BodyFields) > 0 {
				s.HasSkeleton = true
				s.Long = quoteForTemplate(buildLongDoc(op))
				s.SkeletonConst = quoteForTemplate(buildSkeleton(op.BodyFields))
				needsFmt = true
			}
		}
		subs = append(subs, s)
	}
	data := tmplData{
		Tag:           tag,
		GoTag:         goName(tag),
		CLITag:        cliName(tag),
		Subs:          subs,
		NeedsFmt:      needsFmt,
		NeedsUUID:     needsUUID,
		NeedsStrconv:  needsStrconv,
		NeedsOutput:   needsOutput,
		NeedsBindings: needsBindings,
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	out := filepath.Join(outDir, cliName(tag)+".gen.go")
	f, err := os.Create(out)
	if err != nil {
		return err
	}
	defer f.Close()
	return t.Execute(f, data)
}

// assignVerbs picks a unique subcommand verb per operation in a tag group.
//
// Pass 1 derives a candidate verb via operationId stripping (`verbForOp`).
// Pass 2 detects any collisions and replaces each colliding verb with its
// HTTP-method-derived default (`defaultVerbForOp`) — for an `images` group,
// `read_camera_image` and `read_camera_images` both strip to `read-camera`,
// but their defaults are `get` and `list`. Pass 3 asserts uniqueness; if the
// fallback also collides, the generator fails loudly so the spec author sees
// the problem.
func assignVerbs(tag string, ops []Operation) []string {
	verbs := make([]string, len(ops))
	counts := map[string]int{}
	for i, op := range ops {
		v := verbForOp(op)
		verbs[i] = v
		counts[v]++
	}
	for i, op := range ops {
		if counts[verbs[i]] > 1 {
			verbs[i] = defaultVerbForOp(op)
		}
	}
	seen := map[string]string{}
	for i, op := range ops {
		if prior, dup := seen[verbs[i]]; dup {
			panic(fmt.Sprintf("gen-platform-cmds: duplicate subcommand %q for tag %q after fallback: %s and %s collide", verbs[i], tag, prior, op.OperationID))
		}
		seen[verbs[i]] = op.OperationID
	}
	return verbs
}

// verbForOp derives a Cobra subcommand verb from the operation's tag and
// operationId. FastAPI emits operationIds shaped `<tag>-<snake_action>` where
// the action almost always re-includes the resource noun
// (e.g. `devices-push_model_to_device`). We strip:
//
//  1. The `<tag>-` prefix.
//  2. The resource noun in both plural and singular snake form (`devices`,
//     `device`) as whole-word tokens anywhere in the action.
//  3. Trailing prepositions left dangling by step 2 (`_to`, `_from`, ...).
//
// What remains is the operator-meaningful verb. If everything strips away
// (the trivial `list_devices` → ""), we fall back to an HTTP-method-derived
// default. The path is consulted only to disambiguate root GETs (list vs get).
func verbForOp(op Operation) string {
	action := strings.TrimPrefix(op.OperationID, op.Tag+"-")
	for _, noun := range tagNounForms(op.Tag) {
		action = stripWord(action, noun)
	}
	for _, prep := range []string{"_from", "_to", "_of", "_for", "_at", "_in", "_with", "_by", "_on"} {
		action = strings.TrimSuffix(action, prep)
		action = strings.TrimPrefix(action, strings.TrimPrefix(prep, "_")+"_")
	}
	action = strings.Trim(action, "_")
	if action == "" {
		return defaultVerbForOp(op)
	}
	return strings.ReplaceAll(action, "_", "-")
}

// defaultVerbForOp returns the HTTP-method-derived fallback verb, used both
// when verbForOp can't extract a meaningful action and as a tie-breaker when
// multiple operations in a group collapse to the same stripped verb.
func defaultVerbForOp(op Operation) string {
	hasIDParam := strings.Contains(op.Path, "{")
	switch op.Method {
	case "GET":
		if hasIDParam {
			return "get"
		}
		return "list"
	case "POST":
		return "create"
	case "PUT", "PATCH":
		return "update"
	case "DELETE":
		return "delete"
	}
	return "exec"
}

// tagNounForms returns snake_case plural + singular forms of a tag, used to
// strip resource nouns from operationId actions. Tags are kebab-case in
// FastAPI; we convert to snake_case before applying simple English
// pluralization heuristics.
func tagNounForms(tag string) []string {
	plural := strings.ReplaceAll(tag, "-", "_")
	var singular string
	switch {
	case strings.HasSuffix(plural, "ies"):
		singular = plural[:len(plural)-3] + "y"
	case strings.HasSuffix(plural, "ses") || strings.HasSuffix(plural, "xes"):
		singular = plural[:len(plural)-2]
	case strings.HasSuffix(plural, "s") && !strings.HasSuffix(plural, "ss"):
		singular = plural[:len(plural)-1]
	default:
		singular = plural
	}
	if singular == plural {
		return []string{plural}
	}
	return []string{plural, singular}
}

// stripWord removes `word` from s when it appears as a whole token, where a
// token boundary is `_` or the start/end of the string.
func stripWord(s, word string) string {
	s = strings.ReplaceAll(s, "_"+word+"_", "_")
	s = strings.TrimPrefix(s, word+"_")
	s = strings.TrimSuffix(s, "_"+word)
	if s == word {
		s = ""
	}
	return s
}

func exportName(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool { return r == '_' || r == '-' })
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}

func goName(tag string) string {
	return exportName(strings.ReplaceAll(tag, "-", "_"))
}

func cliName(tag string) string {
	return strings.ReplaceAll(strings.ToLower(tag), "_", "-")
}

func escape(s string) string {
	r := strings.NewReplacer(
		"\"", "'",
		"\n", " ",
		"`", "'",
		"\\", "/",
	)
	return r.Replace(s)
}
